!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  acc_lim_theta: 15.0
  acc_lim_trans: 0.27356904308223723
  acc_lim_x: 6.4
  acc_lim_y: 0.0
  angular_sim_granularity: 0.1
  forward_point_distance: 0.325
  goal_distance_bias: 28.0
  groups: !!python/object/new:dynamic_reconfigure.encoding.Config
    dictitems:
      acc_lim_theta: 15.0
      acc_lim_trans: 0.27356904308223723
      acc_lim_x: 6.4
      acc_lim_y: 0.0
      angular_sim_granularity: 0.1
      forward_point_distance: 0.325
      goal_distance_bias: 28.0
      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      id: 0
      max_scaling_factor: 0.2
      max_vel_theta: 9.057886686238938
      max_vel_trans: 0.8816185923631891
      max_vel_x: 0.5497546521927701
      max_vel_y: 0.0
      min_vel_theta: 0.14232107570294295
      min_vel_trans: 0.1745279388943651
      min_vel_x: -3.4420225766692187
      min_vel_y: 0.0
      name: Default
      occdist_scale: 0.01
      oscillation_reset_angle: 10.0
      oscillation_reset_dist: 0.05
      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      parent: 0
      path_distance_bias: 32.0
      prune_plan: true
      restore_defaults: false
      scaling_speed: 0.25
      sim_granularity: 0.025
      sim_time: 1.7
      state: true
      stop_time_buffer: 0.2
      theta_stopped_vel: 0.1
      trans_stopped_vel: 0.1
      twirling_scale: 0.0
      type: ''
      use_dwa: true
      vth_samples: 20
      vx_samples: 3
      vy_samples: 1
      xy_goal_tolerance: 0.3
      yaw_goal_tolerance: 0.3
    state: []
  max_scaling_factor: 0.2
  max_vel_theta: 9.057886686238938
  max_vel_trans: 0.8816185923631891
  max_vel_x: 0.5497546521927701
  max_vel_y: 0.0
  min_vel_theta: 0.14232107570294295
  min_vel_trans: 0.1745279388943651
  min_vel_x: -3.4420225766692187
  min_vel_y: 0.0
  occdist_scale: 0.01
  oscillation_reset_angle: 10.0
  oscillation_reset_dist: 0.05
  path_distance_bias: 32.0
  prune_plan: true
  restore_defaults: false
  scaling_speed: 0.25
  sim_granularity: 0.025
  sim_time: 1.7
  stop_time_buffer: 0.2
  theta_stopped_vel: 0.1
  trans_stopped_vel: 0.1
  twirling_scale: 0.0
  use_dwa: true
  vth_samples: 20
  vx_samples: 3
  vy_samples: 1
  xy_goal_tolerance: 0.3
  yaw_goal_tolerance: 0.3
state: []
